format = """
$time\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
${custom.assume_role}\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""

[aws]
disabled = true

[git_branch]
format = '- [$symbol$branch(:$remote_branch)]($style) '

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = '%F %T'
style = 'fg:7'

[gcloud]
disabled = true

[custom.assume_role]
symbol = '󰆧'
command = 'echo "$AWS_ACCOUNT_NAME/$AWS_ACCOUNT_ROLE" '
style = 'bold fg:178'
when = """
test "$AWS_ACCOUNT_ROLE" -a "$AWS_ACCOUNT_NAME"
"""
format = '- [$symbol $output]($style)'
